# Generated by Django 5.1.3 on 2024-11-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyPassApplication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="suggested",
            field=models.BooleanField(default=False),
        ),
    ]
