# Generated by Django 5.0.6 on 2024-09-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPassApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
