# Generated by Django 5.1.3 on 2024-12-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyPassApplication", "0002_account_suggested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
