# Generated by Django 5.0.6 on 2024-09-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPassApplication', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
