# Generated by Django 5.1.3 on 2024-12-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyPassApplication", "0003_alter_identity_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="license_expiration_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="identity",
            name="passport_expiration_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
