# Generated by Django 5.0.6 on 2024-09-27 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPassApplication', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityquestion',
            old_name='q1Answer',
            new_name='birth_city',
        ),
        migrations.RenameField(
            model_name='securityquestion',
            old_name='q2Answer',
            new_name='favorite_color',
        ),
        migrations.RenameField(
            model_name='securityquestion',
            old_name='q3Answer',
            new_name='first_employer',
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
