# Generated by Django 5.0.6 on 2024-09-27 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPassApplication', '0005_rename_q1answer_securityquestion_birth_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityquestion',
            old_name='birth_city',
            new_name='q1Answer',
        ),
        migrations.RenameField(
            model_name='securityquestion',
            old_name='favorite_color',
            new_name='q2Answer',
        ),
        migrations.RenameField(
            model_name='securityquestion',
            old_name='first_employer',
            new_name='q3Answer',
        ),
    ]
